apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-random-api
  labels:
    app: random-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-api
  template:
    metadata:
      labels:
        app: random-api
    spec:
      containers:
      - name: demo-api-random
        image: demo-api-random:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
